name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *' # 每天一次
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }} #Github Token，记得加入secrets
          owner: firkerword # fork 的上游仓库 user
          base: main # 本地仓库 branch
          head: main # fork 的上游仓库 branch